### PR TITLE
update image

### PR DESCRIPTION
**Pull request by w8896699**
I have pushed the image to bcgov-docker-local:
https://artifacts.developer.gov.bc.ca/ui/repos/tree/General/bcgov-docker-local/crunchy-postgres/ubi8-14.5-1
https://artifacts.developer.gov.bc.ca/ui/repos/tree/General/bcgov-docker-local/crunchy-pgbackrest/ubi8-2.40-1

### CODE REVIEW

**Review by rstens — APPROVED** [review]

**Review by rstens — COMMENTED** [review]
Just to be clear, these 2 new versions fixed the failure in OpenShift 4.12.
It was largely an issue with the pgbackrest image which failed and then proceeds to blocks the deployment of the database pods, because they have pgbackrest as a pre-req to run.

**Comment by w8896699** [comment]
Thanks, Roland for the details!

**Comment by marcellmueller** [comment]
Nice, glad you figured that out.  
  
 Just noticed this merge is blocked as we set this repo to require signed commits to merge since we have been doing it as a best practice.  
  
Let me know if that is an issue, it doesn’t have to be a hard rule.

**Comment by rstens** [comment]
> Nice, glad you figured that out.
> 
> Just noticed this merge is blocked as we set this repo to require signed commits to merge since we have been doing it as a best practice.
> 
> Let me know if that is an issue, it doesn’t have to be a hard rule.

After 5 years working in this environment, this is the first time I encounter the need for a signed commit. From my perspective, this should not be needed as long as the proper roles have been set up and only authorized known people can do a merge.

**Comment by marcellmueller** [comment]
> After 5 years working in this environment, this is the first time I encounter the need for a signed commit. From my perspective, this should not be needed as long as the proper roles have been set up and only authorized known people can do a merge.

Fair enough, I've disabled this.

**Pull request merged**
